import { Job, UserProfile } from './types';

export const MOCK_USER: UserProfile = {
  name: "MOHAMMED RIYAN P",
  photo: "https://picsum.photos/seed/user/200/200",
  qualification: "B.Tech in Computer Science",
  skills: ["Java", "React", "Node.js", "Python", "SQL"],
  appliedCount: 12,
  appliedJobIds: ["1", "4"],
  matchPercentage: 85,
};

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Junior Java Developer",
    company: "Accenture",
    logo: "https://logo.clearbit.com/accenture.com",
    location: "Mumbai, Maharashtra",
    experience: "0-1 Year",
    salary: "₹4.5 - 6.5 LPA",
    skills: ["Java", "Spring Boot", "SQL"],
    tags: ["Fresher", "Immediate Joining", "MNC"],
    description: "We are looking for a passionate Junior Java Developer to join our team. You will be responsible for developing high-quality applications...",
    postedAt: "2 days ago",
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    minSalary: 4.5,
    maxSalary: 6.5,
    website: "https://www.accenture.com",
  },
  {
    id: "2",
    title: "Frontend Developer Intern",
    company: "TCS",
    logo: "https://logo.clearbit.com/tcs.com",
    location: "Bangalore, Karnataka",
    experience: "Fresher",
    salary: "₹3.5 - 5.0 LPA",
    skills: ["React", "JavaScript", "Tailwind CSS"],
    tags: ["Fresher", "Remote", "Urgent"],
    description: "Join TCS as a Frontend Intern and work on cutting-edge projects using React and modern web technologies.",
    postedAt: "1 day ago",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    minSalary: 3.5,
    maxSalary: 5.0,
    website: "https://www.tcs.com",
  },
  {
    id: "3",
    title: "Python Developer",
    company: "Infosys",
    logo: "https://logo.clearbit.com/infosys.com",
    location: "Hyderabad, Telangana",
    experience: "0-2 Years",
    salary: "₹5.0 - 7.0 LPA",
    skills: ["Python", "Django", "REST API"],
    tags: ["Fresher", "Hybrid", "Immediate"],
    description: "Infosys is hiring Python developers who are eager to learn and grow in a fast-paced environment.",
    postedAt: "Just now",
    createdAt: Date.now() - 10 * 60 * 1000,
    minSalary: 5.0,
    maxSalary: 7.0,
    website: "https://www.infosys.com",
  },
  {
    id: "4",
    title: "Associate Software Engineer",
    company: "Wipro",
    logo: "https://logo.clearbit.com/wipro.com",
    location: "Pune, Maharashtra",
    experience: "Fresher",
    salary: "₹4.0 - 5.5 LPA",
    skills: ["C++", "Data Structures", "Algorithms"],
    tags: ["Fresher", "MNC", "Immediate"],
    description: "Wipro is looking for fresh graduates with strong problem-solving skills and a solid foundation in computer science.",
    postedAt: "3 days ago",
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    minSalary: 4.0,
    maxSalary: 5.5,
    website: "https://www.wipro.com",
  },
  {
    id: "5",
    title: "Data Analyst Trainee",
    company: "HCLTech",
    logo: "https://logo.clearbit.com/hcltech.com",
    location: "Noida, Uttar Pradesh",
    experience: "Fresher",
    salary: "₹3.8 - 5.2 LPA",
    skills: ["SQL", "Excel", "Python", "Tableau"],
    tags: ["Fresher", "MNC", "Training Provided"],
    description: "Start your career in data analytics with HCLTech. We provide comprehensive training for freshers to master data visualization and analysis.",
    postedAt: "4 days ago",
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    minSalary: 3.8,
    maxSalary: 5.2,
    website: "https://www.hcltech.com",
  },
  {
    id: "6",
    title: "UI/UX Designer Intern",
    company: "Zomato",
    logo: "https://logo.clearbit.com/zomato.com",
    location: "Gurgaon, Haryana",
    experience: "Fresher",
    salary: "₹25k - 35k / month",
    skills: ["Figma", "Adobe XD", "Prototyping"],
    tags: ["Internship", "Startup", "Remote Friendly"],
    description: "Zomato is looking for creative design interns to help shape the future of food delivery experiences.",
    postedAt: "5 hours ago",
    createdAt: Date.now() - 5 * 60 * 60 * 1000,
    minSalary: 3.0, // 25k/mo * 12 = 3LPA
    maxSalary: 4.2, // 35k/mo * 12 = 4.2LPA
    website: "https://www.zomato.com",
  },
  {
    id: "7",
    title: "Backend Developer (Node.js)",
    company: "Swiggy",
    logo: "https://logo.clearbit.com/swiggy.com",
    location: "Bangalore, Karnataka",
    experience: "0-1 Year",
    salary: "₹8.0 - 12.0 LPA",
    skills: ["Node.js", "Express", "MongoDB", "Redis"],
    tags: ["Fresher", "Startup", "High Growth"],
    description: "Join Swiggy's engineering team to build scalable backend services that power millions of orders daily.",
    postedAt: "1 day ago",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    minSalary: 8.0,
    maxSalary: 12.0,
    website: "https://www.swiggy.com",
  },
  {
    id: "8",
    title: "QA Automation Engineer",
    company: "Cognizant",
    logo: "https://logo.clearbit.com/cognizant.com",
    location: "Chennai, Tamil Nadu",
    experience: "Fresher",
    salary: "₹4.2 - 5.8 LPA",
    skills: ["Selenium", "Java", "Testing", "JUnit"],
    tags: ["Fresher", "MNC", "Immediate"],
    description: "Cognizant is hiring freshers for QA Automation roles. Learn to build robust testing frameworks for global clients.",
    postedAt: "6 days ago",
    createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    minSalary: 4.2,
    maxSalary: 5.8,
    website: "https://www.cognizant.com",
  },
  {
    id: "9",
    title: "Cloud Support Associate",
    company: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    location: "Hyderabad, Telangana",
    experience: "0-1 Year",
    salary: "₹12.0 - 15.0 LPA",
    skills: ["AWS", "Linux", "Networking", "Troubleshooting"],
    tags: ["Fresher", "MNC", "Top Tier"],
    description: "Launch your cloud career at Amazon. Help customers solve complex technical challenges on AWS.",
    postedAt: "2 days ago",
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    minSalary: 12.0,
    maxSalary: 15.0,
    website: "https://www.amazon.jobs",
  },
  {
    id: "10",
    title: "Mobile App Developer (Flutter)",
    company: "Reliance Jio",
    logo: "https://logo.clearbit.com/jio.com",
    location: "Navi Mumbai, Maharashtra",
    experience: "Fresher",
    salary: "₹5.5 - 7.5 LPA",
    skills: ["Flutter", "Dart", "Firebase", "Git"],
    tags: ["Fresher", "Corporate", "Urgent"],
    description: "Jio is looking for Flutter developers to build high-performance mobile applications for millions of users.",
    postedAt: "1 week ago",
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    minSalary: 5.5,
    maxSalary: 7.5,
    website: "https://www.jio.com",
  },
  {
    id: "11",
    title: "Software Engineer I",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    location: "Bangalore, Karnataka",
    experience: "0-2 Years",
    salary: "₹18.0 - 25.0 LPA",
    skills: ["Java", "C++", "Python", "Go"],
    tags: ["Fresher", "MNC", "Top Tier"],
    description: "Google is looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, and large-scale system design.",
    postedAt: "1 day ago",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    minSalary: 18.0,
    maxSalary: 25.0,
    website: "https://careers.google.com",
  },
  {
    id: "12",
    title: "Graduate Engineer Trainee",
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    location: "Hyderabad, Telangana",
    experience: "Fresher",
    salary: "₹15.0 - 20.0 LPA",
    skills: ["C#", ".NET", "Azure", "SQL"],
    tags: ["Fresher", "MNC", "Corporate"],
    description: "Microsoft is hiring fresh graduates for the Graduate Engineer Trainee program. Work on products that empower every person on the planet.",
    postedAt: "3 days ago",
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    minSalary: 15.0,
    maxSalary: 20.0,
    website: "https://careers.microsoft.com",
  },
  {
    id: "13",
    title: "Systems Engineer",
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    location: "Remote",
    experience: "0-1 Year",
    salary: "₹20.0 - 30.0 LPA",
    skills: ["Python", "Linux", "Distributed Systems"],
    tags: ["Fresher", "Remote", "MNC"],
    description: "Join Meta to build the future of connection and help bring the world closer together.",
    postedAt: "2 days ago",
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    minSalary: 20.0,
    maxSalary: 30.0,
    website: "https://www.metacareers.com",
  },
  {
    id: "14",
    title: "Full Stack Developer Trainee",
    company: "Paytm",
    logo: "https://logo.clearbit.com/paytm.com",
    location: "Noida, Uttar Pradesh",
    experience: "Fresher",
    salary: "₹6.0 - 9.0 LPA",
    skills: ["JavaScript", "Node.js", "React", "MongoDB"],
    tags: ["Fresher", "Fintech", "High Growth"],
    description: "Paytm is looking for enthusiastic Full Stack Developer Trainees to build the next generation of digital payments.",
    postedAt: "4 days ago",
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    minSalary: 6.0,
    maxSalary: 9.0,
    website: "https://www.paytm.com",
  },
  {
    id: "15",
    title: "Cyber Security Associate",
    company: "PwC",
    logo: "https://logo.clearbit.com/pwc.com",
    location: "Gurgaon, Haryana",
    experience: "0-1 Year",
    salary: "₹7.5 - 10.5 LPA",
    skills: ["Networking", "Security", "Ethical Hacking"],
    tags: ["Fresher", "Consulting", "MNC"],
    description: "Join PwC's Cyber Security team and help global organizations protect their most valuable digital assets.",
    postedAt: "5 days ago",
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    minSalary: 7.5,
    maxSalary: 10.5,
    website: "https://www.pwc.in",
  },
  {
    id: "16",
    title: "Machine Learning Intern",
    company: "Ola",
    logo: "https://logo.clearbit.com/olacabs.com",
    location: "Bangalore, Karnataka",
    experience: "Fresher",
    salary: "₹40k - 60k / month",
    skills: ["Python", "TensorFlow", "PyTorch", "Math"],
    tags: ["Internship", "AI/ML", "Startup"],
    description: "Ola is looking for ML interns to work on optimizing ride-sharing algorithms and autonomous vehicle tech.",
    postedAt: "1 day ago",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    minSalary: 4.8,
    maxSalary: 7.2,
    website: "https://www.ola.com",
  },
  {
    id: "17",
    title: "DevOps Engineer Trainee",
    company: "Oracle",
    logo: "https://logo.clearbit.com/oracle.com",
    location: "Hyderabad, Telangana",
    experience: "Fresher",
    salary: "₹9.0 - 13.0 LPA",
    skills: ["Docker", "Kubernetes", "Jenkins", "Cloud"],
    tags: ["Fresher", "MNC", "Cloud Infrastructure"],
    description: "Oracle is hiring freshers for DevOps roles. Learn to manage large-scale cloud infrastructure and CI/CD pipelines.",
    postedAt: "2 days ago",
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    minSalary: 9.0,
    maxSalary: 13.0,
    website: "https://www.oracle.com",
  },
  {
    id: "18",
    title: "Business Analyst Intern",
    company: "Flipkart",
    logo: "https://logo.clearbit.com/flipkart.com",
    location: "Bangalore, Karnataka",
    experience: "Fresher",
    salary: "₹30k - 45k / month",
    skills: ["Excel", "SQL", "Communication", "Data Analysis"],
    tags: ["Internship", "E-commerce", "Corporate"],
    description: "Flipkart is looking for Business Analyst interns to help drive data-driven decision making in our supply chain.",
    postedAt: "3 days ago",
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    minSalary: 3.6,
    maxSalary: 5.4,
    website: "https://www.flipkart.com",
  },
  {
    id: "19",
    title: "Java Backend Developer",
    company: "Cisco",
    logo: "https://logo.clearbit.com/cisco.com",
    location: "Pune, Maharashtra",
    experience: "0-2 Years",
    salary: "₹11.0 - 16.0 LPA",
    skills: ["Java", "Spring", "Microservices", "Kafka"],
    tags: ["Fresher", "Networking", "MNC"],
    description: "Join Cisco to build high-performance networking software and cloud-native applications.",
    postedAt: "1 week ago",
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    minSalary: 11.0,
    maxSalary: 16.0,
    website: "https://www.cisco.com",
  },
  {
    id: "20",
    title: "React Native Developer",
    company: "Uber",
    logo: "https://logo.clearbit.com/uber.com",
    location: "Hyderabad, Telangana",
    experience: "Fresher",
    salary: "₹14.0 - 19.0 LPA",
    skills: ["React Native", "JavaScript", "iOS", "Android"],
    tags: ["Fresher", "MNC", "Top Tier"],
    description: "Uber is looking for mobile developers to help build the next generation of our rider and driver apps.",
    postedAt: "2 days ago",
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    minSalary: 14.0,
    maxSalary: 19.0,
    website: "https://www.uber.com",
  },
  {
    id: "21",
    title: "Embedded Systems Engineer",
    company: "Intel",
    logo: "https://logo.clearbit.com/intel.com",
    location: "Bangalore, Karnataka",
    experience: "0-1 Year",
    salary: "₹10.0 - 14.0 LPA",
    skills: ["C", "C++", "RTOS", "Microcontrollers"],
    tags: ["Fresher", "Hardware", "MNC"],
    description: "Intel is hiring freshers for embedded systems roles. Work on the software that powers the world's most advanced processors.",
    postedAt: "4 days ago",
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    minSalary: 10.0,
    maxSalary: 14.0,
    website: "https://www.intel.com",
  },
  {
    id: "22",
    title: "Product Management Trainee",
    company: "Razorpay",
    logo: "https://logo.clearbit.com/razorpay.com",
    location: "Bangalore, Karnataka",
    experience: "Fresher",
    salary: "₹12.0 - 16.0 LPA",
    skills: ["Product Sense", "Analytics", "Communication"],
    tags: ["Fresher", "Fintech", "Startup"],
    description: "Razorpay is looking for PM trainees to help shape the future of payments in India.",
    postedAt: "5 days ago",
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    minSalary: 12.0,
    maxSalary: 16.0,
    website: "https://www.razorpay.com",
  },
  {
    id: "23",
    title: "Software Engineer - Test",
    company: "Salesforce",
    logo: "https://logo.clearbit.com/salesforce.com",
    location: "Hyderabad, Telangana",
    experience: "Fresher",
    salary: "₹13.0 - 18.0 LPA",
    skills: ["Java", "Selenium", "Automation", "Testing"],
    tags: ["Fresher", "SaaS", "MNC"],
    description: "Join Salesforce as a QA Engineer and help us maintain the highest quality standards for our global CRM platform.",
    postedAt: "6 days ago",
    createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    minSalary: 13.0,
    maxSalary: 18.0,
    website: "https://www.salesforce.com",
  }
];

export const POPULAR_SUGGESTIONS = [
  "Java Developer",
  "Frontend Intern",
  "Python Developer",
  "Data Analyst",
  "React Developer",
  "UI/UX Designer",
  "Node.js Backend",
  "Full Stack Trainee",
  "Cloud Engineer",
  "Mobile App Developer",
  "Cyber Security",
  "Machine Learning",
  "DevOps Engineer",
  "QA Automation",
  "Product Management"
];

export const TOP_COMPANIES = [
  { name: "Google", logo: "https://logo.clearbit.com/google.com" },
  { name: "Microsoft", logo: "https://logo.clearbit.com/microsoft.com" },
  { name: "Amazon", logo: "https://logo.clearbit.com/amazon.com" },
  { name: "Meta", logo: "https://logo.clearbit.com/meta.com" },
  { name: "Zomato", logo: "https://logo.clearbit.com/zomato.com" },
  { name: "Swiggy", logo: "https://logo.clearbit.com/swiggy.com" },
  { name: "TCS", logo: "https://logo.clearbit.com/tcs.com" },
  { name: "Accenture", logo: "https://logo.clearbit.com/accenture.com" },
  { name: "Reliance Jio", logo: "https://logo.clearbit.com/jio.com" },
  { name: "HCLTech", logo: "https://logo.clearbit.com/hcltech.com" },
];
